### ISSUE TITLE
wtf you did it in JAVASCRIPT??1?1!1!1?1!1!1!1!

### ISSUE THREAD

**Issue by Arkhtek** [SapphicSapphire/online-play-isnt-rated#1]
literally bad

**Comment by Arkhtek** [comment]
if I could use the soyjack emojis rn I would

(no but actually this is a funny shitpost
science, dude)

**Comment by SapphicSapphire** [comment]
die /j

**Comment by Arkhtek** [comment]
my issue wasn't resolved though???1!1?1!1!1!1
